import { StoryFormValues } from "@/types/StoryType";

export const storyPrompt = ({
  subject,
  type,
  ageGroup,
}: StoryFormValues): string => `
SYSTEM INSTRUCTION:
YOU ARE A JSON-ONLY RESPONSE GENERATOR. YOU MUST FOLLOW ALL RULES EXACTLY.
ANY VIOLATION INVALIDATES THE RESPONSE.

TASK:
CREATE A MAGICAL AND ENGAGING CHILDREN'S STORY BASED ON THE FOLLOWING INPUT:

- TITLE/SUBJECT: ${subject.toUpperCase()}
- STORY TYPE: ${type.toUpperCase()}
- AGE GROUP: ${ageGroup.toUpperCase()}

GLOBAL RULES (MANDATORY):
- OUTPUT MUST BE VALID JSON ONLY
- DO NOT USE MARKDOWN
- DO NOT ADD EXPLANATIONS, COMMENTS, OR EXTRA TEXT
- DO NOT WRAP JSON IN CODE BLOCKS
- DO NOT ADD OR REMOVE JSON KEYS
- DO NOT CHANGE KEY NAMES
- DO NOT ADD NULL VALUES
- DO NOT ADD TRAILING COMMAS
- ALL STRINGS MUST BE DOUBLE-QUOTED
- ALL NUMBERS MUST BE NUMERIC (NOT STRINGS)

STORY CONSTRAINTS:
- LANGUAGE MUST MATCH ${ageGroup.toUpperCase()}
- CONTENT MUST BE SAFE FOR CHILDREN
- STORY MUST BE SPECIFICALLY ABOUT: ${subject.toUpperCase()}
- TONE MUST BE ${type.toUpperCase()}
- INCLUDE POSITIVE VALUES AND A CLEAR MORAL
- EACH PAGE MUST BE SHORT, CLEAR, AND AGE-APPROPRIATE

CHAPTER RULES:
- TOTAL PAGES MUST BE BETWEEN 5 AND 8
- PAGE NUMBERS MUST START AT 1 AND INCREMENT BY 1
- EACH PAGE MUST HAVE:
  - pageNumber (number)
  - title (string)
  - content (string)
  - imagePrompt (string)

IMAGE PROMPT RULES (VERY IMPORTANT):
- imagePrompt MUST BE DETAILED AND DESCRIPTIVE
- DESCRIBE: CHARACTERS, ENVIRONMENT, COLORS, LIGHTING, MOOD, AND ART STYLE
- STYLE MUST BE FRIENDLY, COLORFUL, AND CARTOON-LIKE
- NO TEXT, LETTERS, OR WORDS IN IMAGES
- SUITABLE FOR ${ageGroup.toUpperCase()} CHILDREN
- HIGH-QUALITY CHILDREN'S BOOK ILLUSTRATION STYLE

FAIL CONDITIONS (DO NOT DO THESE):
- DO NOT OUTPUT PARTIAL JSON
- DO NOT OMIT REQUIRED FIELDS
- DO NOT CHANGE THE STRUCTURE
- DO NOT ADD EXTRA ARRAYS OR OBJECTS
- DO NOT RETURN EMPTY STRINGS

FINAL OUTPUT:
RESPOND USING THIS **EXACT** JSON STRUCTURE AND NOTHING ELSE:

{
  "story": {
    "title": "CREATIVE STORY TITLE HERE",
    "description": "SHORT STORY SUMMARY HERE",
    "type": "${type.toUpperCase()}",
    "ageGroup": "${ageGroup.toUpperCase()}",
    "totalPages": 6,
    "imagePrompt": "COVER IMAGE DESCRIPTION HERE",
    "pages": [
      {
        "pageNumber": 1,
        "title": "CHAPTER TITLE HERE",
        "content": "STORY CONTENT HERE",
        "imagePrompt": "PAGE IMAGE DESCRIPTION HERE"
      }
    ]
  }
}
`;
